POST http://localhost:8080/api/users

{
  "email": "user@chirpy.com"
}

###

POST http://localhost:8080/admin/reset

###
POST http://localhost:8080/api/chirps

{
  "body": "Chirp Test 8",
  "user_id": "4a983dd4-5d18-47a7-a145-e15b76b0d387"
}